### ISSUE TITLE
(optionally) keep typed search text in multi-value select after selecting a value from list

### ISSUE THREAD

**Issue by crokitta** [nbuytaert1/apex-select2#40] opened 2015-02-20 13:22 UTC
installed Version: 2.6

When using multi-value select, typing text into the search field, resulting in multiple matches:
selecting one match removes the search text. This is different from behavior in earlier versions and available in the original jQuery plugin too (using CTRL key).
I would like to have this behavior back, or configurable by an option.

regards,
Christian

**Comment by nbuytaert1** [comment] 2015-03-08 11:25
This behaviour is probably caused by the official Select2 plugin, not the APEX plugin. I have updated the library files to the latest and last version of major release 3 (version 3.5.2). The next step would be to upgrade the APEX plugin to Select2 4.0.0. Can you confirm that the above described behaviour is present in version 4.0.0? https://select2.github.io/

If so, then this issue will be automatically fixed when upgrading the plugin's library files.
A temporary solution for you would be to use an old release of the Select2 APEX plugin.

**Comment by nbuytaert1** [comment] 2016-05-16 16:54
This feature will be available in version 3.0.0 by enabling the _Rapid Selection_ attribute. _Rapid Selection_ prevents the dropdown from closing when an item is selected, and remembers the entered search term.

**Closed** 2016-05-31 09:28 UTC
Labels: enhancement
